### ISSUE TITLE
categories 无法正确访问

### ISSUE THREAD

**Issue by Arondight** [slackwarecn/slackwarecn.github.io#1]
[categories](http://slackwarecn.github.io/categories) 访问出现404。

**Comment by Arondight** [comment]
@YanhaoMo  小受求助，求提个PR 或者打个Patch。

**Comment by Yanhao** [comment]
啊咧，学姐你要做slackware社区吗～

**Comment by Arondight** [comment]
不过基本上没有时间……就是想弄个地方，偶尔<s>（百年一遇）</s>去放一些小工具啥的，也不知道会不会有别人一起做。总之自己先这样做着好了。

贴吧发了个帖子，不过好像也很少有人感兴趣，毕竟这个发行版已经隐居多年了。

**Comment by abbycin** [comment]
先下个slackware体验下，说不定就入坑了，学姐说的**小工具**指的是哪些？

**Comment by Arondight** [comment]
目前只有[这一个](https://github.com/slackwarecn/slacklib32)，我想以后有时间的话做一下其他的工具，例如slackware 现在tty 下面没有什么好用的wifi 管理软件，wicd 又年久失修，上一次使用的时候因为python 库的更新已经无法在tty 下面工作了，或者是一些可能带来方便的小东西，例如每个发行版都有自己的chroot 脚本，但是slackware 只能完全手动chroot。或者说slackware 使用BSDinit，但是BSDinit 因为需要手写脚本所以难以统一管理，能不能有一个工具（最好有个dialog 界面）去做这个……总之我觉得想做的话，边边角角可以做挺多东西的。不过还是偶尔去做做就可以了，这个组织主要就是存放大家自用小玩意儿的地方。

另外使用Slackware 的话，建议看一下贴吧的[置顶帖](http://tieba.baidu.com/p/3226065767)，还有，建议等到slackware 14.2 出来之后再去尝试，或者使用最新版的[current iso](http://taper.alienbase.nl/mirrors/slackware/slackware64-current-iso/)。

**Comment by abbycin** [comment]
哦，知道了
